"""Shared recommendation policies (stdlib-only scoring core)."""

from .scoring import (
    ASPECTS_DEFAULT,
    actionable_aspect_ids,
    all_policies,
    competition_aware_scores,
    criticism_metrics,
    diagnostic_largest_gap,
    eligible_aspects,
    explain_action_vs_diagnostic,
    fnum,
    is_finite,
    load_actionability,
    median,
    minmax,
    percentile_rank,
    peer_relative_scores,
    policy_competition_aware,
    policy_fix_weakest,
    policy_largest_peer_gap,
    policy_largest_peer_gap_actionable,
    policy_most_criticized,
    policy_peer_relative,
    policy_reliability_aware,
    ranking_under_intensity,
    reliability,
    sanitize_hotel_numbers,
)

__all__ = [
    "ASPECTS_DEFAULT",
    "actionable_aspect_ids",
    "all_policies",
    "competition_aware_scores",
    "criticism_metrics",
    "diagnostic_largest_gap",
    "eligible_aspects",
    "explain_action_vs_diagnostic",
    "fnum",
    "is_finite",
    "load_actionability",
    "median",
    "minmax",
    "percentile_rank",
    "peer_relative_scores",
    "policy_competition_aware",
    "policy_fix_weakest",
    "policy_largest_peer_gap",
    "policy_largest_peer_gap_actionable",
    "policy_most_criticized",
    "policy_peer_relative",
    "policy_reliability_aware",
    "ranking_under_intensity",
    "reliability",
    "sanitize_hotel_numbers",
]
